import Navbar from "./components/Navbar";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import SessionProviderWrapper from "./components/SessionProviderWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <SessionProviderWrapper>

        <Toaster position="bottom-right" reverseOrder={false} />
        <Navbar />

          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
